"use client";
import { useRef, useState } from "react";
import { parseCsvRows, parseXlsxRows } from "@/lib/import-file";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Upload, Download, Database, CheckCircle, AlertTriangle } from "lucide-react";

const types = [{id:"inventory",label:"Inventory"},{id:"purchase_orders",label:"Purchase orders"},{id:"invoices",label:"Invoices"},{id:"vendors",label:"Vendors"}] as const;
type Kind=typeof types[number]["id"];
type Row=Record<string,unknown>;
const fields:Record<Kind,string[]>={inventory:["materialNumber","description","plant","storageLocation","currentStock","safetyStock","reorderPoint","maxStock","unitOfMeasure","category","supplier","leadTimeDays","unitCost","currency"],purchase_orders:["poNumber","vendorName","materialNumber","description","quantity","unitPrice","totalAmount","currency","status","expectedDelivery","plant"],invoices:["invoiceNumber","vendorName","poNumber","amount","currency","invoiceDate","dueDate","paymentStatus","bankAccountAtInvoice"],vendors:["vendorNumber","name","country","city","taxId","bankAccount","bankName","contactEmail","riskScore","isActive","onWatchlist"]};
const key=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,"");
export function DataImportPanel(){
 const [kind,setKind]=useState<Kind>("inventory"),[rows,setRows]=useState<Row[]>([]),[headers,setHeaders]=useState<string[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[preview,setPreview]=useState<{row:number;valid:boolean;errors:string[]}[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false); const input=useRef<HTMLInputElement>(null);
 const parse=(file:File)=>{setMessage("");const done=(data:Row[])=>{const h=Object.keys(data[0]||{});setRows(data);setHeaders(h);const m:Record<string,string>={};for(const f of fields[kind]){const found=h.find(x=>key(x)===key(f));if(found)m[f]=found;}setMapping(m);setPreview([]);};
 void (async()=>{try{const data=file.name.toLowerCase().endsWith(".csv")?parseCsvRows(await file.text()):parseXlsxRows(await file.arrayBuffer());done(data);}catch(e){setMessage(e instanceof Error?e.message:"Unable to parse the selected file");}})();};
 const mappedRows=()=>rows.map(r=>Object.fromEntries(fields[kind].filter(f=>mapping[f]).map(f=>[f,r[mapping[f]]])));
 const call=async(confirm:boolean)=>{setBusy(true);try{const r=await fetch("/api/data-ingestion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dataset:kind,records:mappedRows(),confirm,fileName:"uploaded file"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");if(!confirm){setPreview(d.results);setMessage(`${d.validCount} valid rows · ${d.errorCount} rows with errors`);}else{setMessage(`Imported ${d.imported} ${types.find(t=>t.id===kind)?.label.toLowerCase()} records · ${d.errorCount} rows need correction`);setRows([]);setHeaders([]);setPreview([]);}}catch(e){setMessage(e instanceof Error?e.message:"Import failed");}finally{setBusy(false);}};
 const demo=async()=>{setBusy(true);try{const r=await fetch("/api/data-ingestion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({demo:true})});const d=await r.json();if(!r.ok)throw new Error(`${d.error||"Unable to load demo dataset"}${d.failedDataset?` (failed dataset: ${d.failedDataset})`:""}`);setMessage(d.demo?`Demo dataset loaded: ${d.imported} records`:(d.error||"Unable to load demo"));}catch(e){setMessage(e instanceof Error?e.message:"Unable to load demo dataset");}finally{setBusy(false);}};
 return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="w-4 h-4 text-[hsl(185_84%_55%)]"/>Enterprise Data Import</CardTitle><p className="text-xs text-slate-500">CSV/XLSX business records · review validation before import · imported data feeds Supply Chain and Fraud</p></CardHeader><CardContent className="space-y-4">
 <div className="flex flex-wrap items-end gap-3"><div className="w-48"><p className="text-xs text-slate-500 mb-1">Dataset</p><Select value={kind} onValueChange={v=>{setKind(v as Kind);setRows([]);setHeaders([]);setPreview([]);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{types.map(t=><SelectItem key={t.id} value={t.id}>{t.label}</SelectItem>)}</SelectContent></Select></div><Button variant="outline" onClick={()=>input.current?.click()}><Upload className="w-4 h-4"/>Choose CSV/XLSX</Button><input ref={input} type="file" accept=".csv,.xlsx,.xls" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)parse(f);}}/><Button variant="outline" onClick={()=>{location.href=`/api/data-ingestion?template=${kind}`;}}><Download className="w-4 h-4"/>Download template</Button><Button onClick={demo} disabled={busy}><Database className="w-4 h-4"/>Load demo dataset</Button></div>
 {rows.length>0&&<><p className="text-xs text-slate-400">{rows.length} rows · map source columns to fields, then validate</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 max-h-52 overflow-auto">{fields[kind].map(f=><label key={f} className="text-xs text-slate-400">{f}<Select value={mapping[f]||"_none"} onValueChange={v=>setMapping(p=>({...p,[f]:v==="_none"?"":v}))}><SelectTrigger className="h-8"><SelectValue placeholder="Not mapped"/></SelectTrigger><SelectContent><SelectItem value="_none">Not mapped</SelectItem>{headers.map(h=><SelectItem key={h} value={h}>{h}</SelectItem>)}</SelectContent></Select></label>)}</div><div className="flex gap-2"><Button variant="outline" onClick={()=>call(false)} disabled={busy}>Validate & preview</Button><Button onClick={()=>call(true)} disabled={busy||preview.length===0||preview.every(x=>!x.valid)}>Confirm import valid rows</Button></div></>}
 {preview.length>0&&<div className="max-h-40 overflow-auto rounded border border-[hsl(222_30%_18%)] p-3 space-y-1">{preview.filter(x=>!x.valid).slice(0,30).map(x=><p key={x.row} className="text-xs text-red-300">Row {x.row}: {x.errors.join("; ")}</p>)}{preview.every(x=>x.valid)&&<p className="text-xs text-emerald-300 flex gap-2"><CheckCircle className="w-4 h-4"/>All rows valid. Confirm import to persist.</p>}</div>}
 {message&&<p className="text-xs text-slate-300 flex gap-2"><AlertTriangle className="w-4 h-4 text-sky-400"/>{message}</p>}
 </CardContent></Card>;
}
